// /api/flutterwave-webhook.js v5
// 1) charge.completed -> activation payments (>=25k). FORM- payments are skipped
//    because verify-form-payment already credits them (fixes double-credit).
//    Activation credits now go through the SHARED finance ledger
//    (creditPaymentOnce in _firebase.js) — the same ledger the verify endpoint
//    uses, so webhook vs callback can NEVER double-credit, in either order.
// 2) AI-* payments (new AI project, SAME Flutterwave account) are NOT ours:
//    we skip crediting them and FORWARD the raw alert to the AI project's
//    webhook endpoint. The election ledger is never touched for AI payments.
// 3) transfer.completed -> withdrawal transfers: finalizes the record + balance
//    EXACTLY ONCE, the moment Flutterwave confirms the money moved.
import { FieldValue } from 'firebase-admin/firestore';
import { getDb, missingFirebaseEnv, creditPaymentOnce, parseActivationYear } from './_firebase.js';

// ================= AI PROJECT FORWARDING CONFIG =================
// Set these in Vercel env vars for the OLD (election) project:
//   AI_PROJECT_WEBHOOK_URL : e.g. https://your-ai-domain.com/api/payments/flutterwave-webhook
//   AI_FORWARD_TOKEN       : long random string — MUST match FLW_FORWARD_TOKEN in the AI project
//   AI_TX_PREFIX           : optional, defaults to 'AI-'
const AI_TX_PREFIX = process.env.AI_TX_PREFIX || 'AI-';
const AI_WEBHOOK_URL = process.env.AI_PROJECT_WEBHOOK_URL || '';
const AI_FORWARD_TOKEN = process.env.AI_FORWARD_TOKEN || '';

// fetch with a hard timeout so a slow/down AI project never holds up
// our 200 response to Flutterwave (works on Node 16+, not just 18+).
function fetchWithTimeout(url, options, ms = 8000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer));
}

// Forwards the raw Flutterwave payload to the AI project's webhook endpoint.
// The AI side authenticates via X-Forward-Token (NOT verif-hash, which is
// only valid for requests coming directly from Flutterwave).
async function forwardToAIProject(payload) {
  if (!AI_WEBHOOK_URL || !AI_FORWARD_TOKEN) {
    console.warn('Webhook: AI forwarding not configured (AI_PROJECT_WEBHOOK_URL / AI_FORWARD_TOKEN missing)');
    return false;
  }
  try {
    const resp = await fetchWithTimeout(AI_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Forward-Token': AI_FORWARD_TOKEN,
      },
      body: JSON.stringify(payload),
    });
    if (!resp.ok) {
      console.error(`Webhook: AI forward returned ${resp.status} ${resp.statusText}`);
      return false;
    }
    console.log(`Webhook: Forwarded ${payload?.data?.tx_ref || 'tx'} to AI project (${resp.status})`);
    return true;
  } catch (error) {
    // AI project unreachable — still return 200 to Flutterwave.
    // The AI project's verify-on-redirect path covers the user's payment.
    console.error('Webhook: AI forward failed:', error.message);
    return false;
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  const flutterwaveSignature = req.headers['verif-hash'];
  const mySecretHash = process.env.Flutterwave_WEBHOOK_SECRET;

  if (!flutterwaveSignature || flutterwaveSignature !== mySecretHash) {
    console.log('Webhook verification failed');
    return res.status(401).json({ message: 'Unauthorized' });
  }

  const payload = req.body || {};

  try {
    if (missingFirebaseEnv.length) {
      return res.status(500).json({ success: false, message: 'Server Firebase env missing: ' + missingFirebaseEnv.join(', ') });
    }
    const db = getDb();

    // ================= CHARGE COMPLETED (activation payments) =================
    if (payload.event === 'charge.completed' && payload.data.status === 'successful') {
      const tx_ref = payload.data.tx_ref || '';

      // ===== NEW: AI project payments (same Flutterwave account) =====
      // tx_refs generated by the AI project start with 'AI-'. These are
      // NOT election payments: skip the election ledger entirely and
      // forward the raw alert to the AI project's webhook endpoint.
      if (String(tx_ref).startsWith(AI_TX_PREFIX)) {
        console.log(`Webhook: AI payment ${tx_ref} — forwarding to AI project`);
        await forwardToAIProject(payload);
        // Always 200: the event was received. If the AI project was down,
        // its verify-on-redirect fallback credits the payment later.
        return res.status(200).json({ status: 'forwarded to AI project' });
      }

      const amount = payload.data.amount;
      const transaction_id = payload.data.id;

      // FORM purchases are credited by /api/verify-form-payment — skip here
      if (String(tx_ref).startsWith('FORM-')) {
        console.log(`Webhook: Skipping form payment ${tx_ref} (credited by verify-form-payment)`);
        return res.status(200).json({ status: 'skipped - form payment' });
      }

      if (Number(amount) < 25000) {
        console.log(`Webhook: Skipping payment under N25,000 (N${amount})`);
        return res.status(200).json({ status: 'skipped - below threshold' });
      }

      // Atomic claim + credit via the SHARED ledger (same one verify-payment uses).
      // "already-credited" / "year-already-activated" here are EXPECTED and safe.
      const result = await creditPaymentOnce({
        transactionId: transaction_id,
        txRef: tx_ref,
        amount,
        kind: 'activation',
      });

      if (result.credited) {
        console.log(`Webhook: Credited N${amount} from transaction ${transaction_id} (${parseActivationYear(tx_ref) || 'unknown'} activated)`);
      } else {
        console.log(`Webhook: Not credited - ${result.reason} (transaction ${transaction_id})`);
      }
      // Always 200: the event was received and handled. A non-credited result
      // is not an error — it means another path already took care of it.
      return res.status(200).json({ status: result.credited ? 'credited' : result.reason });
    }

    // ================= TRANSFER COMPLETED (withdrawals) =================
    if (payload.event === 'transfer.completed') {
      const status = String(payload.data?.status || '').toLowerCase();
      const reference = payload.data?.reference || '';
      const transferId = payload.data?.id || '';
      const amount = Number(payload.data?.amount || 0);

      console.log(`Webhook: transfer.completed ${reference} -> ${status}`);

      if (!reference) {
        return res.status(200).json({ status: 'skipped - no reference' });
      }

      const recordRef = db.collection('withdrawals').doc(reference);

      if (status === 'successful') {
        await db.runTransaction(async (tx) => {
          const cur = await tx.get(recordRef);
          if (cur.exists && cur.data().status === 'successful') return; // already done
          tx.set(recordRef, {
            reference,
            flutterwaveId: transferId ? String(transferId) : (cur.exists ? cur.data().flutterwaveId : ''),
            amount: amount || (cur.exists ? Number(cur.data().amount || 0) : 0),
            status: 'successful',
            verifiedAt: new Date().toISOString()
          }, { merge: true });
          const balRef = db.doc('finances/withdrawalBalance');
          tx.set(balRef, {
            balance: FieldValue.increment(-(amount || (cur.exists ? Number(cur.data().amount || 0) : 0))),
            totalWithdrawn: FieldValue.increment(amount || (cur.exists ? Number(cur.data().amount || 0) : 0)),
            lastWithdrawalAt: new Date().toISOString(),
            lastWithdrawalRef: reference,
            pendingWithdrawal: null
          }, { merge: true });
        });
        console.log(`Webhook: Withdrawal ${reference} CONFIRMED and balance updated`);
      }

      if (status === 'failed') {
        await recordRef.set({ status: 'failed', failedAt: new Date().toISOString() }, { merge: true });
        await db.doc('finances/withdrawalBalance').set({ pendingWithdrawal: null }, { merge: true });
        console.log(`Webhook: Withdrawal ${reference} FAILED - cleared pending lock`);
      }
    }

    return res.status(200).json({ status: 'success' });

  } catch (error) {
    console.error('Webhook error:', error.message);
    return res.status(500).json({ message: 'Internal Server Error' });
  }
}